<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TargettypeController extends Controller
{
    public function index()
    {
        ini_set('max_execution_time', 3600);

        $tgl = Carbon::now();
        // $tgl_now = $tgl->format('Y-m-d');
        $tgl_coba = ['2024-08-29', '2024-08-31'];

        $tartypes = DB::table('wp_w2gm_locations_relationships')
                ->join('wp_term_relationships', 'wp_term_relationships.object_id', '=', 'wp_w2gm_locations_relationships.post_id')
                ->join('wp_term_taxonomy', 'wp_term_taxonomy.term_taxonomy_id', '=', 'wp_term_relationships.term_taxonomy_id')
                ->join('wp_terms', 'wp_terms.term_id', '=', 'wp_term_taxonomy.term_id')
                ->join('wp_posts', 'wp_posts.ID', '=', 'wp_w2gm_locations_relationships.post_id')
                ->select('wp_w2gm_locations_relationships.id', 'wp_terms.name')
                // ->whereDate(DB::raw('DATE(wp_posts.post_date)'), $tgl_now)
                ->whereBetween(DB::raw('DATE(wp_posts.post_date)'), [$tgl_coba[0], $tgl_coba[1]])
                ->where(function($query) {
                    $query->where('wp_terms.term_id', 2930)
                        ->orWhere('wp_terms.term_id', 2931)
                        ->orWhere('wp_terms.term_id', 2932)
                        ->orWhere('wp_terms.term_id', 2929)
                        ->orWhere('wp_terms.term_id', 2823)
                        ->orWhere('wp_terms.term_id', 2822)
                        ->orWhere('wp_terms.term_id', 2821)
                        ->orWhere('wp_terms.term_id', 2824)
                        ->orWhere('wp_terms.term_id', 3002)
                        ->orWhere('wp_terms.term_id', 3003)
                        ->orWhere('wp_terms.term_id', 3004)
                        ->orWhere('wp_terms.term_id', 3001)
                        ->orWhere('wp_terms.term_id', 2879)
                        ->orWhere('wp_terms.term_id', 2878)
                        ->orWhere('wp_terms.term_id', 2877)
                        ->orWhere('wp_terms.term_id', 2880)
                        ->orWhere('wp_terms.term_id', 2991)
                        ->orWhere('wp_terms.term_id', 2990)
                        ->orWhere('wp_terms.term_id', 2989)
                        ->orWhere('wp_terms.term_id', 2992)
                        ->orWhere('wp_terms.term_id', 2906)
                        ->orWhere('wp_terms.term_id', 2907)
                        ->orWhere('wp_terms.term_id', 2908)
                        ->orWhere('wp_terms.term_id', 2905)
                        ->orWhere('wp_terms.term_id', 2818)
                        ->orWhere('wp_terms.term_id', 2819)
                        ->orWhere('wp_terms.term_id', 2820)
                        ->orWhere('wp_terms.term_id', 2817)
                        ->orWhere('wp_terms.term_id', 2895)
                        ->orWhere('wp_terms.term_id', 2894)
                        ->orWhere('wp_terms.term_id', 2893)
                        ->orWhere('wp_terms.term_id', 2896)
                        ->orWhere('wp_terms.term_id', 2986)
                        ->orWhere('wp_terms.term_id', 2987)
                        ->orWhere('wp_terms.term_id', 2988)
                        ->orWhere('wp_terms.term_id', 2985)
                        ->orWhere('wp_terms.term_id', 3015)
                        ->orWhere('wp_terms.term_id', 3014)
                        ->orWhere('wp_terms.term_id', 3013)
                        ->orWhere('wp_terms.term_id', 3016)
                        ->orWhere('wp_terms.term_id', 3023)
                        ->orWhere('wp_terms.term_id', 3022)
                        ->orWhere('wp_terms.term_id', 3021)
                        ->orWhere('wp_terms.term_id', 3024)
                        ->orWhere('wp_terms.term_id', 2874)
                        ->orWhere('wp_terms.term_id', 2875)
                        ->orWhere('wp_terms.term_id', 2876)
                        ->orWhere('wp_terms.term_id', 2873)
                        ->orWhere('wp_terms.term_id', 2927)
                        ->orWhere('wp_terms.term_id', 2926)
                        ->orWhere('wp_terms.term_id', 2925)
                        ->orWhere('wp_terms.term_id', 2928)
                        ->orWhere('wp_terms.term_id', 3010)
                        ->orWhere('wp_terms.term_id', 3011)
                        ->orWhere('wp_terms.term_id', 3012)
                        ->orWhere('wp_terms.term_id', 3009)
                        ->orWhere('wp_terms.term_id', 3018)
                        ->orWhere('wp_terms.term_id', 3019)
                        ->orWhere('wp_terms.term_id', 3020)
                        ->orWhere('wp_terms.term_id', 3017)
                        ->orWhere('wp_terms.term_id', 2871)
                        ->orWhere('wp_terms.term_id', 2870)
                        ->orWhere('wp_terms.term_id', 2869)
                        ->orWhere('wp_terms.term_id', 2872)
                        ->orWhere('wp_terms.term_id', 2922)
                        ->orWhere('wp_terms.term_id', 2923)
                        ->orWhere('wp_terms.term_id', 2924)
                        ->orWhere('wp_terms.term_id', 2921)
                        ->orWhere('wp_terms.term_id', 2807)
                        ->orWhere('wp_terms.term_id', 2806)
                        ->orWhere('wp_terms.term_id', 2805)
                        ->orWhere('wp_terms.term_id', 2808)
                        ->orWhere('wp_terms.term_id', 2882)
                        ->orWhere('wp_terms.term_id', 2883)
                        ->orWhere('wp_terms.term_id', 2884)
                        ->orWhere('wp_terms.term_id', 2881)
                        ->orWhere('wp_terms.term_id', 2839)
                        ->orWhere('wp_terms.term_id', 2838)
                        ->orWhere('wp_terms.term_id', 2837)
                        ->orWhere('wp_terms.term_id', 2840)
                        ->orWhere('wp_terms.term_id', 2911)
                        ->orWhere('wp_terms.term_id', 2910)
                        ->orWhere('wp_terms.term_id', 2909)
                        ->orWhere('wp_terms.term_id', 2912)
                        ->orWhere('wp_terms.term_id', 2914)
                        ->orWhere('wp_terms.term_id', 2915)
                        ->orWhere('wp_terms.term_id', 2916)
                        ->orWhere('wp_terms.term_id', 2913)
                        ->orWhere('wp_terms.term_id', 2919)
                        ->orWhere('wp_terms.term_id', 2918)
                        ->orWhere('wp_terms.term_id', 2917)
                        ->orWhere('wp_terms.term_id', 2920)
                        ->orWhere('wp_terms.term_id', 2938)
                        ->orWhere('wp_terms.term_id', 2931)
                        ->orWhere('wp_terms.term_id', 2940)
                        ->orWhere('wp_terms.term_id', 2937)
                        ->orWhere('wp_terms.term_id', 2815)
                        ->orWhere('wp_terms.term_id', 2814)
                        ->orWhere('wp_terms.term_id', 2813)
                        ->orWhere('wp_terms.term_id', 2816)
                        ->orWhere('wp_terms.term_id', 2983)
                        ->orWhere('wp_terms.term_id', 2982)
                        ->orWhere('wp_terms.term_id', 2981)
                        ->orWhere('wp_terms.term_id', 2984)
                        ->orWhere('wp_terms.term_id', 2850)
                        ->orWhere('wp_terms.term_id', 2851)
                        ->orWhere('wp_terms.term_id', 2852)
                        ->orWhere('wp_terms.term_id', 2849)
                        ->orWhere('wp_terms.term_id', 2943)
                        ->orWhere('wp_terms.term_id', 2942)
                        ->orWhere('wp_terms.term_id', 2941)
                        ->orWhere('wp_terms.term_id', 2944)
                        ->orWhere('wp_terms.term_id', 2970)
                        ->orWhere('wp_terms.term_id', 2971)
                        ->orWhere('wp_terms.term_id', 2972)
                        ->orWhere('wp_terms.term_id', 2969)
                        ->orWhere('wp_terms.term_id', 2959)
                        ->orWhere('wp_terms.term_id', 2958)
                        ->orWhere('wp_terms.term_id', 2957)
                        ->orWhere('wp_terms.term_id', 2960)
                        ->orWhere('wp_terms.term_id', 2999)
                        ->orWhere('wp_terms.term_id', 2998)
                        ->orWhere('wp_terms.term_id', 2997)
                        ->orWhere('wp_terms.term_id', 3000)
                        ->orWhere('wp_terms.term_id', 2954)
                        ->orWhere('wp_terms.term_id', 2955)
                        ->orWhere('wp_terms.term_id', 2956)
                        ->orWhere('wp_terms.term_id', 2953)
                        ->orWhere('wp_terms.term_id', 3026)
                        ->orWhere('wp_terms.term_id', 3027)
                        ->orWhere('wp_terms.term_id', 3028)
                        ->orWhere('wp_terms.term_id', 3025)
                        ->orWhere('wp_terms.term_id', 2866)
                        ->orWhere('wp_terms.term_id', 2867)
                        ->orWhere('wp_terms.term_id', 2868)
                        ->orWhere('wp_terms.term_id', 2865)
                        ->orWhere('wp_terms.term_id', 2802)
                        ->orWhere('wp_terms.term_id', 2803)
                        ->orWhere('wp_terms.term_id', 2804)
                        ->orWhere('wp_terms.term_id', 2801)
                        ->orWhere('wp_terms.term_id', 2834)
                        ->orWhere('wp_terms.term_id', 2835)
                        ->orWhere('wp_terms.term_id', 2836)
                        ->orWhere('wp_terms.term_id', 2833)
                        ->orWhere('wp_terms.term_id', 2826)
                        ->orWhere('wp_terms.term_id', 2827)
                        ->orWhere('wp_terms.term_id', 2828)
                        ->orWhere('wp_terms.term_id', 2825)
                        ->orWhere('wp_terms.term_id', 2967)
                        ->orWhere('wp_terms.term_id', 2966)
                        ->orWhere('wp_terms.term_id', 2965)
                        ->orWhere('wp_terms.term_id', 2968)
                        ->orWhere('wp_terms.term_id', 2831)
                        ->orWhere('wp_terms.term_id', 2830)
                        ->orWhere('wp_terms.term_id', 2829)
                        ->orWhere('wp_terms.term_id', 2832)
                        ->orWhere('wp_terms.term_id', 2903)
                        ->orWhere('wp_terms.term_id', 2902)
                        ->orWhere('wp_terms.term_id', 2901)
                        ->orWhere('wp_terms.term_id', 2904)
                        ->orWhere('wp_terms.term_id', 2935)
                        ->orWhere('wp_terms.term_id', 2934)
                        ->orWhere('wp_terms.term_id', 2933)
                        ->orWhere('wp_terms.term_id', 2936)
                        ->orWhere('wp_terms.term_id', 2863)
                        ->orWhere('wp_terms.term_id', 2862)
                        ->orWhere('wp_terms.term_id', 2861)
                        ->orWhere('wp_terms.term_id', 2864)
                        ->orWhere('wp_terms.term_id', 2946)
                        ->orWhere('wp_terms.term_id', 2947)
                        ->orWhere('wp_terms.term_id', 2948)
                        ->orWhere('wp_terms.term_id', 2945)
                        ->orWhere('wp_terms.term_id', 2810)
                        ->orWhere('wp_terms.term_id', 2811)
                        ->orWhere('wp_terms.term_id', 2812)
                        ->orWhere('wp_terms.term_id', 2809)
                        ->orWhere('wp_terms.term_id', 2978)
                        ->orWhere('wp_terms.term_id', 2979)
                        ->orWhere('wp_terms.term_id', 2980)
                        ->orWhere('wp_terms.term_id', 2977)
                        ->orWhere('wp_terms.term_id', 2890)
                        ->orWhere('wp_terms.term_id', 2891)
                        ->orWhere('wp_terms.term_id', 2892)
                        ->orWhere('wp_terms.term_id', 2889)
                        ->orWhere('wp_terms.term_id', 2887)
                        ->orWhere('wp_terms.term_id', 2886)
                        ->orWhere('wp_terms.term_id', 2885)
                        ->orWhere('wp_terms.term_id', 2888)
                        ->orWhere('wp_terms.term_id', 2898)
                        ->orWhere('wp_terms.term_id', 2899)
                        ->orWhere('wp_terms.term_id', 2900)
                        ->orWhere('wp_terms.term_id', 2897)
                        ->orWhere('wp_terms.term_id', 2994)
                        ->orWhere('wp_terms.term_id', 2995)
                        ->orWhere('wp_terms.term_id', 2996)
                        ->orWhere('wp_terms.term_id', 2993)
                        ->orWhere('wp_terms.term_id', 2855)
                        ->orWhere('wp_terms.term_id', 2854)
                        ->orWhere('wp_terms.term_id', 2853)
                        ->orWhere('wp_terms.term_id', 2856)
                        ->orWhere('wp_terms.term_id', 3007)
                        ->orWhere('wp_terms.term_id', 2962)
                        ->orWhere('wp_terms.term_id', 3006)
                        ->orWhere('wp_terms.term_id', 2963)
                        ->orWhere('wp_terms.term_id', 3005)
                        ->orWhere('wp_terms.term_id', 2964)
                        ->orWhere('wp_terms.term_id', 3008)
                        ->orWhere('wp_terms.term_id', 2961)
                        ->orWhere('wp_terms.term_id', 2975)
                        ->orWhere('wp_terms.term_id', 2974)
                        ->orWhere('wp_terms.term_id', 2973)
                        ->orWhere('wp_terms.term_id', 2976)
                        ->orWhere('wp_terms.term_id', 2847)
                        ->orWhere('wp_terms.term_id', 2846)
                        ->orWhere('wp_terms.term_id', 2845)
                        ->orWhere('wp_terms.term_id', 2553)
                        ->orWhere('wp_terms.term_id', 2842)
                        ->orWhere('wp_terms.term_id', 2843)
                        ->orWhere('wp_terms.term_id', 2844)
                        ->orWhere('wp_terms.term_id', 2841)
                        ->orWhere('wp_terms.term_id', 2951)
                        ->orWhere('wp_terms.term_id', 2950)
                        ->orWhere('wp_terms.term_id', 2949)
                        ->orWhere('wp_terms.term_id', 2952)
                        ->orWhere('wp_terms.term_id', 2791); 
                    })
                ->get();

                if($tartypes->isNotEmpty()){
                    foreach ($tartypes as $tartype){
                        DB::table('pgstatistiks')
                            ->where('id_listing', $tartype->id)
                            ->update([
                                'target_type' => $tartype->name
                            ]);
                    }
                    echo "sukses";
                }else{
                    echo "empty";
                }

    }
}
